# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ds_contrib',
                'doc_host': 'https://apoyezzhayev.github.io',
                'git_url': 'https://github.com/apoyezzhayev/ds_contrib',
                'lib_path': 'ds_contrib'},
  'syms': {'ds_contrib.core': {'ds_contrib.core.foo': ('core.html#foo', 'ds_contrib/core.py')}}}
